CREATE DATABASE GaraDB;

USE GaraDB;

CREATE TABLE LOAIPT (
    MaLoai CHAR(10) PRIMARY KEY,
    TenLoai CHAR(100)
);

CREATE TABLE NHACUNGCAP (
    MaNCC CHAR(10) PRIMARY KEY,
    TenNCC CHAR(80),
    SDT CHAR(12),
    DiaChi CHAR(80)
);

CREATE TABLE NHANVIEN (
    MaNV CHAR(10) PRIMARY KEY,
    HoTen CHAR(50),
    GioiTinh CHAR(10),
    CCCD CHAR(12),
    DiaChi CHAR(80),
    SDT CHAR(10),
    Quyen INT
);
ALTER TABLE NHANVIEN ADD IsDeleted TINYINT(1) DEFAULT 0;
ALTER TABLE NHANVIEN
ALTER COLUMN Quyen SET DEFAULT 0;

CREATE TABLE PHIEUNHAP (
    MaPN CHAR(10) PRIMARY KEY,
    MaNV CHAR(10),
    MaNCC CHAR(10),
    NgayLapPhieu DATETIME,
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

CREATE TABLE PHUTUNG (
    MaPT CHAR(10) PRIMARY KEY,
    MaLoai CHAR(10),
    TenPT CHAR(80),
    DVT CHAR(20),
    GiaThamKhao FLOAT,
    FOREIGN KEY (MaLoai) REFERENCES LOAIPT(MaLoai)
);

CREATE TABLE PHIEUNHAPCT (
    MaPN CHAR(10),
    MaPT CHAR(10),
    DonGia FLOAT,
    SoLuong INT,
    PRIMARY KEY (MaPN, MaPT),
    FOREIGN KEY (MaPN) REFERENCES PHIEUNHAP(MaPN),
    FOREIGN KEY (MaPT) REFERENCES PHUTUNG(MaPT)
);

CREATE TABLE BANGTONKHO (
    MaTK CHAR(10),
    MaPT CHAR(10),
    GhiChu CHAR(255),
    PRIMARY KEY (MaTK, MaPT),
    FOREIGN KEY (MaPT) REFERENCES PHUTUNG(MaPT)
);

CREATE TABLE ChuXe (
    MaCX CHAR(10) PRIMARY KEY,
    HoTen CHAR(50),
    DiaChi CHAR(80),
    SDT CHAR(10)
);

CREATE TABLE HIEUXE (
    MaHX CHAR(10) PRIMARY KEY,
    TenHX CHAR(20)
);

INSERT INTO HIEUXE (MaHX, TenHX) VALUES ('HX001', 'Toyota');
INSERT INTO HIEUXE (MaHX, TenHX) VALUES ('HX002', 'Honda');
INSERT INTO HIEUXE (MaHX, TenHX) VALUES ('HX003', 'Ford');
INSERT INTO HIEUXE (MaHX, TenHX) VALUES ('HX004', 'Chevrolet');
INSERT INTO HIEUXE (MaHX, TenHX) VALUES ('HX005', 'Nissan');
INSERT INTO HIEUXE (MaHX, TenHX) VALUES ('HX006', 'BMW');
INSERT INTO HIEUXE (MaHX, TenHX) VALUES ('HX007', 'Mercedes');
INSERT INTO HIEUXE (MaHX, TenHX) VALUES ('HX008', 'Hyundai');
INSERT INTO HIEUXE (MaHX, TenHX) VALUES ('HX009', 'Kia');
INSERT INTO HIEUXE (MaHX, TenHX) VALUES ('HX010', 'Mazda');

CREATE TABLE XE (
    MaBX CHAR(10) PRIMARY KEY,
    MaCX CHAR(10),
    MaHX CHAR(10),
    MoTa CHAR(255),
    FOREIGN KEY (MaCX) REFERENCES ChuXe(MaCX),
    FOREIGN KEY (MaHX) REFERENCES HIEUXE(MaHX)
);

CREATE TABLE QUIDINH (
    MaQD CHAR(10) PRIMARY KEY,
    MaxTienCong FLOAT,
    MaxHieuXe INT
);

CREATE TABLE PHIEUTIEPNHAN (
    MaTN CHAR(10) PRIMARY KEY,
    MaBX CHAR(10),
    MaNV CHAR(10),
    GhiChu CHAR(255),
    FOREIGN KEY (MaBX) REFERENCES XE(MaBX),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE PHIEUSUAXE (
    MaPSX CHAR(10) PRIMARY KEY,
    MaTN CHAR(10),
    MaNV CHAR(10),
    NgaySua DATETIME,
    FOREIGN KEY (MaTN) REFERENCES PHIEUTIEPNHAN(MaTN),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE PHIEUSUACT (
    MaPSX CHAR(10),
    MaPT CHAR(10),
    NoiDung CHAR(255),
    TienCong FLOAT,
    DonGia FLOAT,
    PRIMARY KEY (MaPSX, MaPT),
    FOREIGN KEY (MaPSX) REFERENCES PHIEUSUAXE(MaPSX),
    FOREIGN KEY (MaPT) REFERENCES PHUTUNG(MaPT)
);

CREATE TABLE NGUOIDUNG (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL,
    MaCX CHAR(10),
    MaNV CHAR(10),
    FOREIGN KEY (MaCX) REFERENCES ChuXe(MaCX),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);
INSERT INTO NGUOIDUNG (username, password, email, role, MaCX, MaNV) 
VALUES ('admin', SHA2('123', 256), 'admin@gmail.com', 'admin', NULL, NULL);
UPDATE NGUOIDUNG 
SET MaNV = '1'
WHERE username = 'admin';

SELECT * FROM nhanvien;
SELECT * FROM ChuXe; 
SELECT * FROM NGUOIDUNG 
	JOIN NHANVIEN NV ON NV.MaNV = NGUOIDUNG.MaNV 
	LEFT JOIN ChuXe CX ON CX.MaCX = NGUOIDUNG.MaCX
	Where username = 'admin';
INSERT INTO NHANVIEN (MaNV, HoTen, GioiTinh, CCCD, DiaChi, SDT, Quyen)
VALUES ('1', 'Admin', 'Nam', '123456789012', '123 Duong ABC, TP HCM', '0901234567', 1);